#!/bin/sh

VER=$1
SUB=$2

rm -f repack_zip/emp/zImage
rm -f magisk_module/system/vendor/lib/modules/*.ko

if [ ! -d magisk_module/system/vendor ]; then
	mkdir magisk_module/system/vendor
	mkdir magisk_module/system/vendor/lib
	mkdir magisk_module/system/vendor/lib/modules
fi

###not use -dtb for now
cp out/arch/arm64/boot/Image.gz-dtb repack_zip/emp/zImage
###
#cp out/arch/arm64/boot/Image.gz repack_zip/emp/kernel
#cat repack_zip/emp/kernel repack_zip/emp/dtb.img > repack_zip/emp/zImage
#rm repack_zip/emp/kernel
cd out
find -name "*.ko" -exec mv {} ../magisk_module/system/vendor/lib/modules \;
cd ..
repack_zip/emp/strip --strip-unneeded magisk_module/system/vendor/lib/modules/*
mv magisk_module/system/vendor/lib/modules/wlan.ko magisk_module/system/vendor/lib/modules/qca_cld3_wlan.ko
###fake modules
touch magisk_module/system/vendor/lib/modules/texfat.ko
touch magisk_module/system/vendor/lib/modules/bu520x1nvx.ko
touch magisk_module/system/vendor/lib/modules/fpc1145_platform.ko
touch magisk_module/system/vendor/lib/modules/ldo_vibrator.ko
#touch magisk_module/system/vendor/lib/modules/mpq-adapter.ko
#touch magisk_module/system/vendor/lib/modules/mpq-dmx-hw-plugin.ko
touch magisk_module/system/vendor/lib/modules/nxp_pn553_nfc.ko
touch magisk_module/system/vendor/lib/modules/p73.ko
#touch magisk_module/system/vendor/lib/modules/rdbg.ko
touch magisk_module/system/vendor/lib/modules/sim_detect.ko
touch magisk_module/system/vendor/lib/modules/spi-qup-qcom-cloned.ko
touch magisk_module/system/vendor/lib/modules/synaptics_tcm_core.ko
touch magisk_module/system/vendor/lib/modules/synaptics_tcm_device.ko
touch magisk_module/system/vendor/lib/modules/synaptics_tcm_diagnostics.ko
touch magisk_module/system/vendor/lib/modules/synaptics_tcm_i2c.ko
touch magisk_module/system/vendor/lib/modules/synaptics_tcm_recovery.ko
touch magisk_module/system/vendor/lib/modules/synaptics_tcm_reflash.ko
touch magisk_module/system/vendor/lib/modules/synaptics_tcm_testing.ko
touch magisk_module/system/vendor/lib/modules/synaptics_tcm_touch.ko
#touch magisk_module/system/vendor/lib/modules/qca_cld3_wlan.ko
###

cd repack_zip
zip -r SOV42_EMP_Kernel_Beta.zip *
mv SOV42_EMP_Kernel_Beta.zip ../
cd ../magisk_module
zip -r SOV42_EMP_Kernel_modules_magisk.zip *
mv SOV42_EMP_Kernel_modules_magisk.zip ../
cd ..
echo "--------------------------------------------------"
echo "-              Repack      Completed             -"
echo "--------------------------------------------------"
echo "-              kernel  by rote66                 -"
echo "--------------------------------------------------"
echo "-Cutting Edge Aftermarket Sony Phone Technology-"
echo "--------------------------------------------------"
